
---
- name: Create Security Group {{ osp_security_group.name }}
  os_security_group:
    cloud: "{{ osp_cloud }}"
    name: "{{ osp_security_group.name }}"

- name: Create Security Group Rule Apps
  os_security_group_rule:
    cloud: "{{ osp_cloud }}"
    security_group: "{{ osp_security_group.name }}"
    protocol: "{{ rule.protocol | default('tcp') }}"
    port_range_min: "{{ rule.port }}"
    port_range_max: "{{ rule.port }}"
    remote_ip_prefix: "{{ rule.ip_prefix | default('0.0.0.0/0') }}"
  loop: "{{ osp_security_group.rules | default([]) }}"
  loop_control:
    loop_var: rule
    label: "{{ rule.port }}"
